name = "crm-cloudflare-app"
compatibility_date = "2024-12-15"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
workers_dev = true

assets = { binding = "ASSETS", directory = "./public" }

[vars]
ALLOWED_ORIGINS = "*"

[[d1_databases]]
binding = "DB"
database_name = "crm-cloudflare-app-db"
database_id = "42f5b376-0e32-49d9-8f8f-f22028f4c26d"

[[r2_buckets]]
binding = "FILES"
bucket_name = "crm-cloudflare-app-files"
preview_bucket_name = "crm-cloudflare-app-files-dev"

[[kv_namespaces]]
binding = "CACHE"
id = "6c551091e4554abf8afcf6befa1db72d"
preview_id = "78a18a45560d4d6782389af88e1f4f5b"
