name = "crmforall"
compatibility_date = "2024-12-15"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
workers_dev = true

assets = { binding = "ASSETS", directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "crmforall-db"
database_id = "68cd9034-6e88-420c-8584-3a521726e26a"

[[r2_buckets]]
binding = "FILES"
bucket_name = "crmforall-files"
preview_bucket_name = "crmforall-files-dev"

[[kv_namespaces]]
binding = "CACHE"
id = "REPLACE_WITH_KV_ID"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID"
