#!/bin/bash

# Deployment script for CRM Cloudflare App
# Sets AUTH_SECRET as Cloudflare Workers secret, deploys, and provides database setup instructions

set -e

echo "?? Starting deployment..."

# Check if wrangler is installed
if ! command -v wrangler &> /dev/null; then
    echo "? wrangler not found. Please install it: npm install -g wrangler"
    exit 1
fi

# Load environment variables from .env if it exists
if [ -f .env ]; then
    echo "?? Loading environment variables from .env"
    export $(grep -v '^#' .env | xargs)
fi

# Check if AUTH_SECRET is set
if [ -z "$AUTH_SECRET" ]; then
    echo "? AUTH_SECRET is not set. Please set it in .env or environment variables."
    exit 1
fi

echo "?? Setting AUTH_SECRET as Cloudflare Workers secret..."
echo "$AUTH_SECRET" | wrangler secret put AUTH_SECRET

echo "Building analytics bundle..."
npm run build:analytics

echo "?? Deploying Cloudflare Worker..."
wrangler deploy -c wrangler.toml

echo "? Deployment complete!"
echo ""
echo "?? IMPORTANT: Database and User Setup"
echo "====================================="
echo "If users cannot login (e.g., mark.wu@taicounty.com.tw with password '1@Nissanka'), you may need to:"
echo ""
echo "1. Initialize database and create admin user:"
echo "   ./scripts/init-database.sh"
echo ""
echo "2. Or manually run the SQL generated by:"
echo "   node scripts/generate-password-hash.js '1@Nissanka' 'mark.wu@taicounty.com.tw' 'Admin'"
echo ""
echo "3. Check if database schema is initialized:"
echo "   The schema auto-initializes on first API call to /api/* endpoints."
echo ""
echo "4. Create admin user if none exists (bootstrap):"
echo "   Make a POST request to /api/auth/login with:"
echo "   {"
echo "     \"email\": \"mark.wu@taicounty.com.tw\","
echo "     \"password\": \"1@Nissanka\","
echo "     \"name\": \"Admin\""
echo "   }"
echo ""
echo "5. If bootstrap doesn't work (users already exist), use the init script:"
echo "   ./scripts/init-database.sh --email 'mark.wu@taicounty.com.tw' --password '1@Nissanka'"
echo ""
echo "For more help, see README.md troubleshooting section."
